# IMPORTS

In [1]:
import os
from classes.layers.Conv2D import Conv2D
from classes.layers.Dense import Dense
from classes.layers.Flatten import Flatten
from classes.layers.Input import InputLayer
from classes.models.Sequential import Sequential
from classes.utils.ImageConvert import ImageConvert

# DATA PREPROCESSING

In [2]:
# TEST
## Constructor
import numpy as np
# c2d_layer_1 = Conv2D(1, (2, 2))
# c2d_layer_2 = Conv2D(
#     2, (4, 4), conv_stride=1, conv_padding_size=2,
#     activation='relu',
#     pool_kernel_size=9,
#     pool_stride=2,
#     pool_mode='avg',
#     name='c2d_l2')

# ## Class preview
# ### Conv kernels
# print(c2d_layer_1.conv_filters)
# print(c2d_layer_2.conv_filters)
## Compile
c2d_test = Conv2D(
    2, (2,2),
    conv_stride=1, conv_padding_size=0,
    activation='relu',
    pool_kernel_size=(2,2), pool_stride=1,
    pool_mode='max')
print("TYPE TEST:", type(c2d_test) is Conv2D)
c2d_test.compile((None, 6, 6, 5))
## Calculate
c2d_test.calculate(np.random.rand(6, 6, 5))
print('input')
print(c2d_test.input)
print(c2d_test.input.shape)
print()
print()
print('conv')
print(c2d_test.conv_output)
print(c2d_test.conv_output.shape)
print(c2d_test.conv_output[:,:,0])
print()
print()
print('filter')
print(c2d_test.conv_filters)
print(c2d_test.conv_filters[0])
print()
print()
print('output')
print(c2d_test.output)
print(c2d_test.output.shape)
# ## Detector
# test_detector = Conv2D(1, (2,2))
# test_detector_array = np.array([[[2, 7.2341], [-6,-0.1226]],
#             [[0,-0.1763],[-1,12.316872]]])
# print(test_detector_array)
# print()
# print()
# test_detector_result = test_detector.detect(test_detector_array)
# print(test_detector_result)
# print("TEST SHAPE :", test_detector_array.shape == test_detector_result.shape)
# ## Pooling
# test_pool_1 = Conv2D(
#     1, (2,2),
#     pool_kernel_size=(2,2),
#     pool_stride=1,
#     pool_mode='max',
# )
# test_pool_array = np.array([[[2, 7.2341], [-6, -0.1226]],
#             [[0, -0.1763],[-1, 12.316872]]])
# print(test_pool_array)
# print(test_pool_array.shape)
# test_pool_result = test_pool_1.pool(test_pool_array)
# print(test_pool_result)
# print(test_pool_result.shape)
c3d_test = Conv2D(
    2, (2,2),
    conv_stride=1, conv_padding_size=0,
    activation='relu',
    pool_kernel_size=(2,2), pool_stride=1,
    pool_mode='max')
print("TYPE TEST:", type(c2d_test) is Conv2D)
c3d_test.compile((None, 4, 4, 2))
## Calculate
c3d_test.calculate(np.random.rand(4, 4, 2))
print("----------")
c2d_test.backward(next_layer = c3d_test)
print(c2d_test.delta_pools)
print(c2d_test.delta_detectors)
print(c2d_test.delta_pools[0].shape)
print(c2d_test.delta_detectors[0].shape)
print('deltas')
print(c2d_test.deltas)

TYPE TEST: True
input
[[[7.56104889e-01 3.97338483e-01 3.42326056e-01 5.55668190e-01
   4.29727284e-01]
  [1.65381816e-01 5.75399850e-01 3.29748775e-02 6.77395209e-01
   2.61090636e-01]
  [8.86823188e-01 5.49354767e-01 5.57426716e-01 9.38426291e-01
   7.57443044e-01]
  [3.92516311e-01 7.99146995e-03 9.68239637e-01 6.65582145e-02
   5.39667914e-01]
  [1.93333231e-02 6.04785546e-01 9.04698023e-01 3.76340899e-01
   2.63199867e-01]
  [8.72695096e-01 5.20738236e-01 1.05073586e-01 5.41599337e-01
   4.79267927e-01]]

 [[3.24524716e-01 1.55097674e-01 1.35231969e-01 2.85379367e-01
   7.67579241e-01]
  [5.07030423e-01 9.28661398e-01 9.82302164e-01 5.18388792e-01
   2.37146560e-02]
  [8.77511300e-01 2.73744047e-01 1.75352061e-01 5.69681113e-01
   8.74815302e-01]
  [6.29765540e-01 4.49881987e-01 4.97398805e-01 2.67604595e-02
   6.69117210e-01]
  [8.93554152e-01 5.79018508e-02 1.92852212e-01 7.11431184e-01
   4.03160711e-01]
  [1.89632915e-01 3.91422411e-01 4.09156560e-01 1.30634256e-01
   9.099951

TypeError: 'NoneType' object is not subscriptable

In [2]:
ic_train = ImageConvert(
        rotate=30.,
        rescale=1./255.)
data_train_gen = ic_train.from_directory(os.path.join('.','data','train'), (256,256), mode='binary', color_mode='rgb')

ic_test = ImageConvert(
        rotate=30.,
        rescale=1./255.)
data_test_gen = ic_test.from_directory(os.path.join('.','data','test'), (256,256), mode='binary', color_mode='rgb')

In [3]:
X_train = []
y_train = []

for i in range(len(data_train_gen)):
    step = next(data_train_gen)
    X_train.append(step['data'])
    y_train.append(step['label'])

X_test = []
y_test = []

for i in range(len(data_test_gen)):
    step = next(data_test_gen)
    X_test.append(step['data'])
    y_test.append(step['label'])

# MODEL

## Instantiating

In [4]:
model = Sequential([
        InputLayer(input_shape=(256,256,3)),
        Conv2D(2, (16, 16), activation='relu'),
        Flatten(),
        Dense(16, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

model.compile()

## Training

In [6]:
model.fit(X_train, y_train, 20, 10, 0.2, verbose=True)

TypeError: 'NoneType' object is not subscriptable

## Testing

In [7]:
# TEST
model.predict(X_test)

[array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.])]